code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Controllers/ResellersController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FunTokenz.Filter;
using FunTokenz.Models.Business;
using FunTokenz.Models.Data;
using FunTokenz.Models.View;
using FunTokenz.Services;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using System.Text;
using Stripe;
using Amazon.SimpleNotificationService;
using System.Globalization;
using Amazon.SimpleNotificationService.Model;
using System.Security.Cryptography;
using System.Linq;


namespace FunTokenz.Controllers
{

    [Authorize]
    [ValidateSessionAttribute]
    public class ResellersController : BaseController
    {

        private readonly ILogger<ResellersController> _logger;
        private readonly IIdentity _Identity;
        private readonly IRDS _RDS;
        private readonly IComms _Comms;
        private readonly UserManager<ApplicationUser> _userManager;

        public ResellersController(
                ILogger<ResellersController> logger,
                IIdentity Identity,
                IRDS RDS,
                IComms Comms,
                UserManager<ApplicationUser> userManager
        ) : base(logger, RDS, userManager)
        {
            _logger = logger;
            _Identity = Identity;
            _userManager = userManager;
            _RDS = RDS;
            _Comms = Comms;
        }

        [HttpGet]
        [MustBeSignedIn]
        [RestrictedResellerArea]
        [RestrictedResellerValidatedArea]
        [Route("/resellers/home")]
        public IActionResult Home()
        {
            ResellerTransactionsView model = new ResellerTransactionsView();
            model.TransactionRecords = _RDS.GetResellerTransactions(new Options() { Filter = new Models.Business.Filter(), Results = new Results() { pageNumber = 1, pageSize = 5 } });
            return View(model);
        }

        [HttpPost]
        [MustBeSignedIn]
        [RestrictedResellerArea]
        [RestrictedResellerValidatedArea]
        [Route("/resellers/home")]
        public IActionResult Home([FromBody] Results result)
        {
            ResellerTransactionsView model = new ResellerTransactionsView();
            model.TransactionRecords = _RDS.GetResellerTransactions(new Options() { Filter = new Models.Business.Filter(), Results = new Results() { pageNumber = result.pageNumber, pageSize = result.pageSize } });
            return PartialView("_Transactions", model.TransactionRecords);
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("/resellers/faq")]
        public IActionResult FAQ()
        {
            GeneralView view = new GeneralView();
            view.Title = "Resellers FAQ";
            view.ContentSection = new ContentSection();
            return View("General", view);
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("/resellers/awaiting-approval")]
        public IActionResult AwaitingApproval()
        {
            
            SettingsModel model = new SettingsModel();
            var result = _userManager.FindByIdAsync(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            Task.WhenAll(result);
            model.User = result.Result;
            model.AccountValidations = _RDS.GetFiles();

            return View(model);
        }


        /* * */

        [HttpGet]
        [MustBeSignedIn]
        [RestrictedResellerArea]
        [RestrictedResellerValidatedArea]
        [Route("/resellers/buy")]
        public IActionResult Buy(Int32 token)
        {
            _logger.LogInformation("Reseller Buy Loaded");
            ResellerPurchaseForm model = new ResellerPurchaseForm();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [MustBeSignedIn]
        [RestrictedResellerArea]
        [RestrictedResellerValidatedArea]
        [Route("/resellers/confirm")]
        public IActionResult Confirm([FromForm] ResellerPurchaseForm model)
        {
            _logger.LogInformation("Reseller Confirm Loaded");
            if (ModelState.IsValid)
            {
                _logger.LogInformation("Reseller PreSet Purchase");

                var exchange = "";
                if (HttpContext.Session.GetString("ResellerCurrency") == "PGK")
                {
                    exchange = _RDS.GetExchangeRate("PGK", "AUD");
                }
                else if (HttpContext.Session.GetString("ResellerCurrency") == "FJD")
                {
                    exchange = _RDS.GetExchangeRate("FJD", "AUD");
                }

                var charge = ((model.Amount * Convert.ToDecimal(1.05)) / Convert.ToDecimal(exchange)).ToString("0.##");
                model.ExchangeRate = Convert.ToDecimal(exchange);
                model.ChargeAmount = Convert.ToDecimal(charge);
                model.ResellerCurrency = HttpContext.Session.GetString("ResellerCurrency");

                HttpContext.Session.SetString("Amount", charge);
                HttpContext.Session.SetString("Value", model.Amount.ToString("0.##"));

                // Set the Purchase
                var save = _RDS.SetResellerPurchase(model);

                return View(model);
            }
            else
            {
                return View("Buy", model);
            }
        }

        [HttpPost]
        [MustBeSignedIn]
        [RestrictedResellerArea]
        [RestrictedResellerValidatedArea]
        public async Task<IActionResult> Charge([FromForm] StripePayment charge)
        {
            _logger.LogInformation("Reseller Charge called: ");

            try
            {
                var time = DateTime.Now.ToUniversalTime().ToString("yyyyMMddHHmmssffff");

                if (!string.IsNullOrEmpty(charge.stripeToken) && HttpContext.Session.GetString("Amount") == charge.Amount.ToString())
                {
                    // Get User
                    var user = await _userManager.FindByIdAsync(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);

                    string customerRef = "";
                    if (!string.IsNullOrEmpty(user.StripeCustomerRef))
                    {
                        // Update Customer
                        var update = new CustomerUpdateOptions
                        {
                            Source = charge.stripeToken,
                        };
                        var serviceUpdate = new CustomerService();
                        var updateResponse = serviceUpdate.Update(user.StripeCustomerRef, update);

                        customerRef = user.StripeCustomerRef;
                    }
                    else
                    {
                        // Create Customer
                        var customer = new CustomerCreateOptions
                        {
                            Email = user.Email,
                            Name = user.Firstname + " " + user.Lastname,
                            Phone = user.PhoneNumber,
                            Source = charge.stripeToken,
                        };
                        var services = new CustomerService();
                        var created = services.Create(customer);

                        customerRef = created.Id;

                        // Save Customer Reference
                        var setCustomerReference = await _Identity.SetStripeCustomerRef(customerRef);

                    }

                    // Create Payment
                    var options = new ChargeCreateOptions
                    {
                        Amount = Convert.ToInt32(charge.Amount * 100),
                        Currency = "aud",
                        Customer = customerRef
                    };
                    var service = new ChargeService();
                    var payment = service.Create(options);

                    // Update Purchase
                    var save = _RDS.UpdateResellerPurchase(null, null, payment.Id, Convert.ToDecimal(HttpContext.Session.GetString("Value")));

                    _logger.LogInformation("Reseller Purchase Finalised: " + save);

                    var balance = await _Identity.UpdateResellerBalance(Convert.ToDecimal(HttpContext.Session.GetString("Value")));
                    HttpContext.Session.SetString("ResellerBalance", balance.ToString());

                    _logger.LogInformation("Reseller Balance Updated: " + balance);

                    return View("Success");

                }
            }
            catch (StripeException exc)
            {
                _logger.LogError("Stripe Error: " + exc);

            }
            _logger.LogInformation("Charge: J");

            return View("Failed");

        }

        /* Sale */

        [HttpGet]
        [MustBeSignedIn]
        [RestrictedResellerArea]
        [RestrictedResellerValidatedArea]
        [Route("/resellers/sale")]
        public IActionResult Sale(Int32 token)
        {

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var current_user = _userManager.FindByIdAsync(userId);

            if (current_user.Result.ResellerBalance == 0)
            {
                ModelState.AddModelError("", "Your balance is zero.");
                ResellerTransactionsView m = new ResellerTransactionsView();
                m.TransactionRecords = _RDS.GetResellerTransactions(new Options() { Filter = new Models.Business.Filter(), Results = new Results() { pageNumber = 1, pageSize = 5 } });
                return View("Home", m);
            }


            _logger.LogInformation("Reseller Sale Loaded");
            CustomerSaleView model = new CustomerSaleView();
            model.CustomerRecords = _RDS.GetResellerCustomers(new Options() { Filter = new Models.Business.Filter(), Results = new Results() { pageNumber = 1, pageSize = 2500 } });

            return View(model);
        }

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Resellers/Buy.cshtml
@using Microsoft.AspNetCore.Http;

@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}

@{
    ViewData["Title"] = "Step 1";
}

@model ResellerPurchaseForm


@section Styles
    {
    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 0em;
        }

        .breadcrumb-1 {
            background: #F4F9FE;
        }

        .form-group.custom-bg {
            background-color: #F4F5F7;
            width: 100%;
            align-items: center;
            padding: 25px 30px;
            margin-bottom: 20px;
            border-radius: 5px;
        }

        .panel1 {
            padding: 28px;
            margin: 20px 0px 30px 0px;
            border: 1px solid rgba(150, 200, 250, 0.1);
            background: rgba(150, 200, 250, 0.1);
            box-shadow: 0px 0px 20px rgb(0 0 0 / 30%);
            border: 10px solid #FFF;
            border-radius: 10px;
        }

        .panel {
            margin: 20px 0px 30px 0px;
            padding: 14px;
            border: 1px solid rgba(150, 200, 250, 0.1);
        }

        .total {
            text-align: right;
            color: #303030;
            padding: 16px 36px;
            background: #f1f1f1;
            font-weight: 600;
        }

        .tokens-list {
            width: 100%;
            margin-top: 10px;
        }

        .text-left {
            text-align: left !important;
        }

        .each-token {
            width: 100%;
            flex-direction: row;
            padding: 20px 28px;
            background-color: #F4F5F7;
            justify-content: space-between;
            margin-top: 16px;
        }

        .text-danger {
            color: #dc3545 !important;
        }

        .each-token h5.price {
            text-align: right;
            font-weight: 600;
        }

        .token-info span {
            text-align: left;
            color: #868a9a;
        }

        .token-info h5 {
            text-align: left;
            color: #15294b;
            margin-bottom: 10px;
        }

        .each-token h5.price span {
            font-size: 14px;
            font-weight: 600;
            background: #FFF;
            border-radius: 3px;
            padding: 2px;
            color: #15294b;
        }

        .mt-4, .my-4 {
            margin-top: 1.5rem !important;
        }

        .align-items-center {
            -ms-flex-align: center !important;
            align-items: center !important;
        }

        .d-flex {
            display: -ms-flexbox !important;
            display: flex !important;
        }

        .mr-2, .mx-2 {
            margin-right: 0.5rem !important;
        }

        .d-md-none {
            display: none !important;
        }

        img {
            vertical-align: middle;
            border-style: none;
        }

        .mt-3, .my-3 {
            margin-top: 1rem !important;
        }

        .w-100 {
            width: 100% !important;
        }

        .rates .rate input[type='text'] {
            padding: 10px;
            font-size: 1.3em;
            margin-bottom: 10px;
            border: 1px solid #f1f1f1;
            width: 100%;
            box-shadow: 0px 0px 10px rgba(0,0,0,0.15);
        }

        .btn-grey {
            margin-top: 20px;
            background-color: rgba(150, 200, 250, 0.1);
            text-align: center;
            color: #303030;
            padding: 15px 30px;
            width: fit-content;
        }

        .btn {
            transition: .2s transform;
        }

        .font-weight-bold {
            font-weight: 700 !important;
        }

        button:not(:disabled), [type="button"]:not(:disabled), [type="reset"]:not(:disabled), [type="submit"]:not(:disabled) {
            cursor: pointer;
        }

        .btn:focus, .btn.focus {
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }

        .btn:focus, .btn:active:focus, .btn.active:focus, .btn.focus, .btn:active.focus, .btn.active.focus {
            outline: thin dotted;
            outline: 5px auto #00000000;
            outline-offset: -2px;
        }

        .form-group.custom-bg input, .form-group.text-left input {
            padding: 16px;
            margin-top: 5px;
            border: 0px;
            font-weight: 600;
        }
    </style>
}

<div class="container-fluid breadcrumb-1" style="margin-top: 8.1em">
    <div class="row">
        <p style="padding: 0.5em 0 0 1em"><a href="~/">Home</a> . <a href="~/resellers/home">Resellers Home</a> . Bulk Purchase Tokenz</p>
    </div>
</div>


<div class="banner_bottom">
    <div class="container">
        <div class="inner_sec_info_wthree_agile">
            <div class="help_full">
                <div class="col-md-3 col-xs-12 banner_bottom_grid help"></div>
                <div class="col-md-6 col-xs-12 banner_bottom_grid help">
                    <h2 class="page-mobile-title">Add to your balance</h2>
                    <p class="text-md-left">Your purchase currency is: <b>@Context.Session.GetString("ResellerCurrency")</b>.<br /><br />Enter the amount of tokens you wish to purchase (1 Token = 1 @Context.Session.GetString("ResellerCurrency")).</p>
                    <form asp-controller="Resellers" asp-action="Confirm" method="post" class="w-100 mt-2">
                        <div asp-validation-summary="All" class="text-danger text-left"></div>
                        <div class="form-group custom-bg">
                           <div class="row">
                               <div class="col-md-5 col-sm-5">
                                   <label>How Many Fun Tokens: <sub><br />Minimum of: 1000.00</sub></label>
                               </div>
                               <div class="col-md-7 col-sm-7">
                                   <input type="text" asp-for="Amount" value="1000.00" class="form-control" />
                               </div>     
                           </div>
                        </div>
                        

                        <button type="submit" class="btn btn-block btn-danger mt-4 font-weight-bold">REVIEW PURCHASE</button>
                    </form>

                </div>
                <div class="col-md-3 col-xs-12 banner_bottom_grid help"></div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Resellers/Confirm.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}

@{
    ViewData["Title"] = "Step 2";
}

@model ResellerPurchaseForm

@section Styles
{
    <link href="~/css/stripe.css" rel="stylesheet" type="text/css" media="all">

    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 0em;
        }

        .breadcrumb-1 {
            background: #F4F9FE;
        }

        .token-name {
            background-color: #F4F5F7;
            text-align: center;
            width: 100%;
            padding: 40px;
        }

        span.mobile {
            background: #F4F5F7;
            padding: 18px;
            display: block;
            width: auto;
        }

        .card-payment {
            flex-direction: column;
        }

        .d-flex {
            display: -ms-flexbox !important;
            display: flex !important;
        }

        .example.example2 {
            background-color: #fff;
        }

        .payment-form ul {
            list-style: none;
            margin: 0px;
            padding: 0px;
        }

        .payment-form ul li {
            margin: 0px;
            padding: 0px;
        }

        .example.example2 * {
            font-family: Source Code Pro, Consolas, Menlo, monospace;
            font-size: 16px;
            font-weight: 500;
        }

        .btn-danger {
            margin-top: 20px;
            background-color: rgba(233,72,89,1);
            text-align: center;
            color: #fff;
            padding: 15px;
        }
    </style>
}



@section ScriptsTop
{
    <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript" src="~/js/stripemain.js" data-rel-js></script>
}

@section Scripts
{
    <script type="text/javascript" src="~/js/popper.min.js"></script>
    <script type="text/javascript" src="~/js/stripe.js" data-rel-js></script>
}


<div class="container-fluid breadcrumb-1" style="margin-top: 8.1em">
    <div class="row">
        <p style="padding: 0.5em 0 0 1em"><a href="~/">Home</a> . <a href="~/resellers/home">Resellers Home</a> . Reseller Bulk Purchase</p>
    </div>
</div>





<div class="banner_bottom">
    <div class="container">
        <div class="inner_sec_info_wthree_agile">
            <div class="help_full">
                <div class="col-md-6 col-xs-12 banner_bottom_grid help">
                    <h2 class="text-left w-100">Bulk Fun Tokenz Purchase</h2>
                    <p class="my-3 page-mobile-title">Confirm your purchase of tokenz.</p>
                    <div class="token-name mt-2 mt-md-3">
                        <h3>@Model.Amount</h3>
                        <span>in Fun Tokenz</span>
                    </div>
                    <p class="my-4 font-23">You will be charged <b>@Model.ChargeAmount AUD</b>  inc 2.50% surcharge</p>
                    <div class="d-flex justify-content-center w-100 mb-4 only-mobile">
                        <img src="images/slide_swipe.svg" alt="">
                    </div>
                    <p class="my-4 w-100 text-left">Upon purchase your tokens will be added to your Reselle Balance</p>

                </div>
                <div class="col-md-6 col-xs-12 banner_bottom_left">
                    <div class="d-flex card-payment">
                        <h3 class="text-left w-100">Enter your Card for Secure Payment</h3>
                        <div class="payment-form">
                            <form asp-controller="Resellers" asp-action="Charge" name="formToken" id="formToken" method="post" class="form-horizontal">
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="stripeToken" id="stripeToken" value="" />
                                <input type="hidden" name="Amount" id="Amount" value="@Model.ChargeAmount" />
                            </form>
                            <div class="cell example example2" id="example-2">
                                <form asp-controller="Account" asp-action="XXX" method="post" class="form-horizontal">
                                    @Html.AntiForgeryToken()
                                    <ul>
                                        <li>
                                            <div id="example2-card-number" class="input empty"></div>
                                            <label for="example2-card-number" data-tid="elements_examples.form.card_number_label">Card Number</label>
                                            <div class="baseline"></div>
                                        </li>
                                        <li class="inline">
                                            <div id="example2-card-expiry" class="input empty"></div>
                                            <label for="example2-card-expiry" data-tid="elements_examples.form.card_expiry_label">Expiration</label>
                                            <div class="baseline"></div>
                                        </li>
                                        <li class="inline">
                                            <div id="example2-card-cvc" class="input empty"></div>
                                            <label for="example2-card-cvc" data-tid="elements_examples.form.card_cvc_label">CVC</label>
                                            <div class="baseline"></div>
                                        </li>
                                        <li>
                                            <button type="submit" class="btn" data-tid="elements_examples.form.pay_button">Pay &amp; Complete Order</button>
                                            <div class="error" role="alert">
                                                <span class="message"></span>
                                            </div>
                                        </li>
                                    </ul>
                                </form>
                            </div>
                        </div>
                    </div>

                    <a href="~/resellers/buy" class="btn btn-block btn-danger" style="margin-top: 8px">Or Go back</a>

                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Resellers/Failed.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}

@{
    ViewData["Title"] = "Purchase Failed";
}

@model PurchaseForm

@section Styles
    {
    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 8em;
        }
    </style>
}

<div class="banner_bottom">
    <div class="container">
        <div class="inner_sec_info_wthree_agile">
            <div class="help_full" id="PurchaseResult">
                <h2 class="text-center">Your Bulk Purchase Failed</h2>
                <p class="text-center" style="font-size:1.2em;">We were unable to complete your purchase, <a href="~/resellers/buy">click here to try and purchase FunTokenz</a> once more.</p>
            </div>
        </div>
    </div>
</div>

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Resellers/RedeemConfirm.cshtml
@using Microsoft.AspNetCore.Http;

@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}

@{
    ViewData["Title"] = "Step 2";
}

@model CustomerRedeemForm

@section Styles
{
    <link href="~/css/stripe.css" rel="stylesheet" type="text/css" media="all">

    <style>
       
        .inner_sec_info_wthree_agile {
            margin-top: 0em;
        }

        .breadcrumb-1 {
            background: #F4F9FE;
        }

        .token-name {
            background-color: #F4F5F7;
            text-align: center;
            width: 100%;
            padding: 40px;
        }

        .card-payment {
            flex-direction: column;
        }

        .example.example2 * {
            font-family: Source Code Pro, Consolas, Menlo, monospace;
            font-size: 16px;
            font-weight: 500;
        }

        .payment-form ul {
            list-style: none;
            margin: 0px;
            padding: 0px;
        }

        .btn-danger {
            margin-top: 20px;
            background-color: rgba(233,72,89,1);
            text-align: center;
            color: #fff;
            padding: 15px;
        }
    </style>
}

@section ScriptsTop
{
    <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript" src="~/js/stripemain.js" data-rel-js></script>
}

@section Scripts
{
    <script type="text/javascript" src="~/js/popper.min.js"></script>
    <script type="text/javascript" src="~/js/stripe.js" data-rel-js></script>
}



<div class="container-fluid breadcrumb-1" style="margin-top: 8.1em">
    <div class="row">
        <p style="padding: 0.5em 0 0 1em"><a href="~/">Home</a> . <a href="~/resellers/home">Resellers Home</a> . Reseller Bulk Purchase</p>
    </div>
</div>



<div class="banner_bottom">
    <div class="container">
        <div class="inner_sec_info_wthree_agile">
            <div class="help_full">
                <div class="col-md-3 col-xs-12 banner_bottom_grid help"></div>

                <div class="col-md-6 col-xs-12 banner_bottom_grid help">
                    
                    <h2 class="text-left">Fun Tokenz Redemption</h2>
                    <p class="my-3 page-mobile-title">Confirm the redemption of the tokenz.</p>
                    <div class="token-name mt-2 mt-md-3">
                        <h3>@Model.Amount</h3>
                        <span>in Fun Tokenz</span>
                    </div>
                    <p class="font-23">Your customer is to be given <b>@Context.Session.GetString("ResellerCurrency") @Context.Session.GetString("RedeemAmount")</b>.<br /><br /><b>Congrats on your buy back!</b>, this withdrawal will earn you <b>@Math.Abs(((Convert.ToDecimal(Context.Session.GetString("RedeemAmount")) - Convert.ToDecimal(Context.Session.GetString("RedeemValue"))) / Convert.ToDecimal(Context.Session.GetString("RedeemValue"))) * 100)%</b> profit.</p>
                    <div class="justify-content-center mb-4 only-mobile">
                        <img src="images/slide_swipe.svg" alt="">
                    </div>
                    <p class="text-left">
                        Upon confirmation @Model.Amount tokens will be deposited in your reseller account.
                    </p>

                    <div class="card-payment">
                        <h3 class="text-left">Pay <b>@Context.Session.GetString("ResellerCurrency") @Context.Session.GetString("RedeemAmount")</b> to your customer and click confirm below. Make sure you click confirm below.</h3>
                        <div class="payment-form">
                            <div class="cell example example2" id="example-2">
                                <form asp-controller="Resellers" asp-action="RedeemProcess" method="post" class="form-horizontal">
                                    <input type="hidden" asp-for="UserId" />
                                    <input type="hidden" asp-for="Amount" value="@Model.Amount" />
                                    <input type="hidden" asp-for="Phone" value="@Model.Phone" />
                                    <input type="hidden" asp-for="Email" value="@Model.Email" />
                                    <input type="hidden" asp-for="FunTokenzCode1" value="@Model.FunTokenzCode1" />
                                    <input type="hidden" asp-for="FunTokenzCode2" value="@Model.FunTokenzCode2" />
                                    <input type="hidden" asp-for="FunTokenzCode3" value="@Model.FunTokenzCode3" />
                                    <input type="hidden" asp-for="FunTokenzCode4" value="@Model.FunTokenzCode4" />
                                    <input type="hidden" asp-for="FunTokenzCode5" value="@Model.FunTokenzCode5" />
                                    <input type="hidden" asp-for="FunTokenzCode6" value="@Model.FunTokenzCode6" />
                                    <input type="hidden" asp-for="FunTokenzCode7" value="@Model.FunTokenzCode7" />
                                    <input type="hidden" asp-for="FunTokenzCode8" value="@Model.FunTokenzCode8" />
                                    <input type="hidden" asp-for="CountryCode" value="@Model.CountryCode" />
                                    @Html.AntiForgeryToken()
                                    <ul>
                                        <li>
                                            <button type="submit" class="btn" data-tid="elements_examples.form.pay_button">Confirm &amp; Complete Redemption</button>
                                            <div class="error" role="alert">
                                                <span class="message"></span>
                                            </div>
                                        </li>
                                    </ul>
                                </form>
                            </div>
                        </div>
                    </div>

                    <a href="~/resellers/redeem" class="btn btn-block btn-danger">Or Go back</a>

                </div>

                <div class="col-md-3 col-xs-12 banner_bottom_grid help"></div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Resellers/RedeemFailed.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}

@{
    ViewData["Title"] = "Customer Redemption Failed";
}


@section Styles
    {
    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 8em;
        }
    </style>
}

<div class="banner_bottom">
    <div class="container">
        <div class="inner_sec_info_wthree_agile">
            <div class="help_full" id="PurchaseResult">
                <h2 class="text-center">The Redemption Failed</h2>
                <p class="text-center" style="font-size:1.2em;">We were unable to complete the redemption, <a href="~/resellers/redeem">click here to try and redeem the FunTokenz</a> once more.</p>
            </div>
        </div>
    </div>
</div>

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Resellers/RedeemSuccess.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}


@{
    ViewData["Title"] = "Customer Redemption Success";
}

@section Styles
    {
    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 8em;
        }
    </style>
}

<div class="banner_bottom">
    <div class="container">
        <div class="inner_sec_info_wthree_agile">
            <div class="help_full" id="PurchaseResult">
                <h2 class="text-center">The Redemption Was Successful</h2>
                <p class="text-center" style="font-size:1.2em;">We have deposited the redemmed FunTokenz into your reseller account.</p>
            </div>
        </div>
    </div>
</div>

   