code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Controllers/CustomersController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FunTokenz.Filter;
using FunTokenz.Models.Business;
using FunTokenz.Models.Data;
using FunTokenz.Models.View;
using FunTokenz.Services;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using System.Text;
using Stripe;
using Amazon.SimpleNotificationService;
using System.Globalization;
using Amazon.SimpleNotificationService.Model;
using System.Linq;
using System.Collections.Generic;

namespace FunTokenz.Controllers
{

    [Authorize]
    [ValidateSessionAttribute]
    public class CustomersController : BaseController
    {

        private readonly ILogger<CustomersController> _logger;
        private readonly IIdentity _Identity;
        private readonly IRDS _RDS;
        private readonly IComms _Comms;
        private readonly UserManager<ApplicationUser> _userManager;

        public CustomersController(
                ILogger<CustomersController> logger,
                IIdentity Identity,
                IRDS RDS,
                IComms Comms,
                UserManager<ApplicationUser> userManager
        ) : base(logger, RDS, userManager)
        {
            _logger = logger;
            _Identity = Identity;
            _userManager = userManager;
            _RDS = RDS;
            _Comms = Comms;
        }


        [HttpGet]
        [MustBeSignedIn]
        [RestrictedCustomerArea]
        [Route("/customers/home")]
        public IActionResult Home()
        {
            PurchasesView model = new PurchasesView();
            model = _RDS.GetPurchases(new Options() { Filter = new Models.Business.Filter(), Results = new Results() { pageNumber = 1, pageSize = 3 } });
            return View(model);
        }

        [HttpPost]
        [MustBeSignedIn]
        [RestrictedCustomerArea]
        [Route("/customers/home")]
        public IActionResult Home([FromBody] Results result)
        {
            PurchasesView model = new PurchasesView();
            model = _RDS.GetPurchases(new Options() { Filter = new Models.Business.Filter(), Results = new Results() { pageNumber = result.pageNumber, pageSize = result.pageSize } });
            return PartialView("_Tokens",model);
        }

        [HttpGet]
        [MustBeSignedIn]
        [RestrictedCustomerArea]
        [Route("/customers/tokens/{token}")]
        public IActionResult Token(Int32 token)
        {
            PurchaseView model = new PurchaseView();
            model = _RDS.GetPurchase(token);
            return View(model);
        }

        [HttpGet]
        [MustBeSignedIn]
        [RestrictedCustomerArea]
        [Route("/Customers/buy")]
        public IActionResult Buy(Int32 token)
        {
            _logger.LogInformation("Buy Loaded");
            PurchaseForm model = new PurchaseForm();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [MustBeSignedIn]
        [RestrictedCustomerArea]
        [Route("/customers/confirm")]
        public IActionResult Confirm([FromForm] PurchaseForm model)
        {
            _logger.LogInformation("Confirm Loaded");
            if (ModelState.IsValid)
            {
                _logger.LogInformation("PreSet Purchase");

                var exchange = "0.00001";
                if (model.Currency == "PGK")
                {
                    exchange = _RDS.GetExchangeRate("PGK", "AUD");
                   
                }
                else if (model.Currency == "FJD")
                {
                    exchange = _RDS.GetExchangeRate("FJD", "AUD");
                }
                
                var charge = ((model.Amount * Convert.ToDecimal(1.05)) / Convert.ToDecimal(exchange)).ToString("0.##");
                model.ExchangeRate = Convert.ToDecimal(exchange);
                model.ChargeAmount = Convert.ToDecimal(charge);

                HttpContext.Session.SetString("Amount", charge);
                HttpContext.Session.SetString("Value", model.Amount.ToString("0.##"));

                // Set the Purchase
                var save = _RDS.SetPurchase(model, false, null, "AUD");

                return View(model);
            }
            else
            {
                return View("Buy", model);
            }
        }

        [HttpPost]
        [MustBeSignedIn]
        [RestrictedCustomerArea]
        public async Task<IActionResult> Charge([FromForm] StripePayment charge)
        {
            _logger.LogInformation("Charge Loaded");
            try
            {
                _logger.LogInformation("Charge - A: " + HttpContext.Session.GetString("Amount") + " | " + charge.Amount.ToString());
                var time = DateTime.Now.ToUniversalTime().ToString("yyyyMMddHHmmssffff");

                if (!string.IsNullOrEmpty(charge.stripeToken) && HttpContext.Session.GetString("Amount") == charge.Amount.ToString())
                {
                    _logger.LogInformation("Charge: B");
                    // Get User
                    var user = await _userManager.FindByIdAsync(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);

                    string customerRef = "";
                    if (!string.IsNullOrEmpty(user.StripeCustomerRef))
                    {
                        _logger.LogInformation("Charge: C");
                        // Update Customer
                        var update = new CustomerUpdateOptions
                        {
                            Source = charge.stripeToken,
                        };
                        var serviceUpdate = new CustomerService();
                        var updateResponse = serviceUpdate.Update(user.StripeCustomerRef, update);

                        customerRef = user.StripeCustomerRef;

                        _logger.LogInformation("Charge: C: " + customerRef);
                    }
                    else
                    {
                        _logger.LogInformation("Charge: D");
                        // Create Customer
                        var customer = new CustomerCreateOptions
                        {
                            Email = user.Email,
                            Name = user.Firstname + " " + user.Lastname,
                            Phone = user.PhoneNumber,
                            Source = charge.stripeToken,
                        };
                        var services = new CustomerService();
                        var created = services.Create(customer);

                        _logger.LogInformation("Charge: D Result: " + JsonConvert.SerializeObject(created));

                        customerRef = created.Id;

                        // Save Customer Reference
                        var setCustomerReference = await _Identity.SetStripeCustomerRef(customerRef);

                        _logger.LogInformation("Charge: D: " + customerRef);
                    }
                    _logger.LogInformation("Charge: E");

                    // Create Payment
                    var options = new ChargeCreateOptions
                    {
                        Amount = Convert.ToInt32(charge.Amount * 100),
                        Currency = "aud",
                        Customer = customerRef
                    };
                    var service = new ChargeService();
                    var payment = service.Create(options);

                    _logger.LogInformation("Charge: G | " + payment.Id + " | " + charge.Amount + " | " + Convert.ToDecimal(HttpContext.Session.GetString("Value")));

                    // Update Purchase
                    var save = _RDS.UpdatePurchase(null, null, payment.Id, Convert.ToDecimal(HttpContext.Session.GetString("Value")));

                    _logger.LogInformation("Charge: H");

                    // Save and send Token
                    if (save > 0)
                    {
                        _logger.LogInformation("Charge: 2");
                        // Send the SMS
                        var token = _RDS.GetToken(save);

                        _logger.LogInformation("Charge: 3");

                        if (token != null && !string.IsNullOrEmpty(token.Code))
                        {
                            _logger.LogInformation("Send SMS: " + token.Code);

                            var expiry = DateTime.ParseExact(token.ExpiryTime.ToString(), "yyyyMMddHHmmssffff", CultureInfo.InvariantCulture).ToString("dd MMM yyyy");

                            var sb = new StringBuilder()
                                .Append("Hello, a FunTokenz.com user has sent you tokens for use with our partners.\n\n")
                                .Append("You have been given: " + token.Currency + token.Value + "\n\n")
                                .Append("Your token code is: " + token.Code + "\n\n")
                                .Append("Valid Till: " + expiry);
                            var message = sb.ToString();

                            AmazonSimpleNotificationServiceClient snsClient = new AmazonSimpleNotificationServiceClient(Amazon.RegionEndpoint.EUCentral1);
                            PublishRequest pubRequest = new PublishRequest();
                            pubRequest.Message = message;
                            pubRequest.PhoneNumber = token.Phone;
                            pubRequest.MessageAttributes.Add("AWS.SNS.SMS.SenderID", new MessageAttributeValue { StringValue = "FunTokenz", DataType = "String" });
                            pubRequest.MessageAttributes.Add("AWS.SNS.SMS.SMSType", new MessageAttributeValue { StringValue = "Transactional", DataType = "String" });
                            var pubResponse = await snsClient.PublishAsync(pubRequest);

                            _logger.LogInformation("Charge: 4");

                        }

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Customers/Confirm-Paypal-Version.cshtml
@{
    ViewData["Title"] = "Step 2";
}

@model PurchaseForm

@section Scripts{

    @*Staging*@
    @*<script src="https://www.paypal.com/sdk/js?client-id=Ae-lNt9InPWN_9FeMOvSTCgQ268eoGGIogcbWEYfFkgM1u_AXmQ8wOLsAzQ6XLgJPKueAB7Y7j0LocWs&currency=EUR"></script>*@
    <script src="https://www.paypal.com/sdk/js?client-id=AdUz2eOEfgJhfEMYy3lQsYk-NNxtayuBn9sythrcefN9H5MFVxr_ZfROSJeYyATWoZEXpjvMwy4ds-gp&currency=EUR"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function (data, actions) {
                return actions.order.create({
                    intent: "capture",
                    purchase_units: [{
                        amount: {
                            value: '@Model.ChargeAmount',
                            currency_code: 'EUR'
                        }
                    }],
                    application_context: {
                        shipping_preference: 'NO_SHIPPING',
                        user_action: 'PAY_NOW'
                    }
                });
            },

            // Finalize the transaction
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (orderData) {

                    var forgeryId = $('[name="__RequestVerificationToken"]').val();
                    var datax = { "JSON": JSON.stringify(orderData, null, 2), "Ref" : orderData.id };

                    $.ajax("/finalise", {
                        method: "POST",
                        timeout: 4000,
                        data: JSON.stringify(datax),
                        contentType: 'application/json; charset=utf-8',
                        headers: {
                            'RequestVerificationToken': forgeryId
                        },
                        beforeSend: function () {
                        },
                        success: function (datax) {
                            $("#PurchaseResult").html(datax);
                        },
                        error: function () {
                            console.log("error");
                        }
                    });


                });
            }


        }).render('#paypal-button-container');
    </script>
}

<main>
    <div class="container">
        <div class="row">
            <div class="col-md-7 p-0 desktop-visual">
                <img src="images/payment.png" alt="payment" class="hero-img">
            </div>
            <div class="col-12 d-flex justify-content-center py-4 only-mobile">
                <img src="images/step4_screen.png" alt="">
            </div>
            <div class="col-md-5 d-flex align-items-start flex-column justify-content-center content-section content-section-bg text-center" id="PurchaseResult">
                <h1 class="text-left w-100">Fun Tokenz Purchase</h1>
                <p class="my-3 page-mobile-title">Confirm your purchase of tokens.</p>
                <div class="token-name mt-2 mt-md-3">
                    <h3>@Model.Amount</h3>
                    <span>in Fun Tokenz</span>
                </div>
                <p class="my-4 font-23">You will be charged <b>@Model.ChargeAmount EURO</b>  inc 2.50% surcharge</p>
                <div class="d-flex justify-content-center w-100 mb-4 only-mobile">
                    <img src="images/slide_swipe.svg" alt="">
                </div>
                <p class="my-4 w-100 text-left">Upon purchase your tokens will be sent to:<br /> <span class="mobile">@Model.CountryCode @Model.Phone</span></p>

                <div id="paypal-button-container" class="w-100"></div>
                <a href="~/buy" class="btn btn-block btn-danger mt-4">Or Go back</a>

            </div>
        </div>
    </div>
</main>

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Customers/Confirm.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}

@{
    ViewData["Title"] = "Step 2";
}

@model PurchaseForm

@section Styles
{
    <link href="~/css/stripe.css" rel="stylesheet" type="text/css" media="all">

   <style>
       .inner_sec_info_wthree_agile {
           margin-top: 0em;
       }

       .breadcrumb-1 {
           background: #F4F9FE;
       }

       .token-name {
           background-color: #F4F5F7;
           text-align: center;
           width: 100%;
           padding: 40px;
       }

       span.mobile {
           background: #F4F5F7;
           padding: 18px;
           display: block;
           width: auto;
       }

       .card-payment {
           flex-direction: column;
       }

       .d-flex {
           display: -ms-flexbox !important;
           display: flex !important;
       }

       .example.example2 {
           background-color: #fff;
       }

       .payment-form ul {
           list-style: none;
           margin: 0px;
           padding: 0px;
       }

        .payment-form ul li {
            margin: 0px;
            padding: 0px;
        }

       .example.example2 * {
           font-family: Source Code Pro, Consolas, Menlo, monospace;
           font-size: 16px;
           font-weight: 500;
       }

       .btn-danger {
           margin-top: 20px;
           background-color: rgba(233,72,89,1);
           text-align: center;
           color: #fff;
           padding: 15px;
       }
    </style>
}



@section Scripts
{
    <script type="text/javascript" src="~/js/popper.min.js"></script>
    <script type="text/javascript" src="~/js/stripe.js" data-rel-js></script>
}


<div class="container-fluid breadcrumb-1" style="margin-top: 8.1em">
    <div class="row">
        <p style="padding: 0.5em 0 0 1em"><a href="~/">Home</a> . <a href="~/customers/home">My Wallet</a> . Purchase Tokenz</p>
    </div>
</div>





<div class="banner_bottom">
    <div class="container">
        <div class="inner_sec_info_wthree_agile">
            <div class="help_full">
                <div class="col-md-6 col-xs-12 banner_bottom_grid help">
                    <h2 class="text-left w-100">Fun Tokenz Purchase</h2>
                    <p class="my-3 page-mobile-title">Confirm your purchase of tokens.</p>
                    <div class="token-name mt-2 mt-md-3">
                        <h3>@Model.Amount</h3>
                        <span>in Fun Tokenz</span>
                    </div>
                    <p class="my-4 font-23">You will be charged <b>@Model.ChargeAmount AUD</b>  inc 2.50% surcharge</p>
                    <div class="d-flex justify-content-center w-100 mb-4 only-mobile">
                        <img src="images/slide_swipe.svg" alt="">
                    </div>
                    <p class="my-4 w-100 text-left">Upon purchase your tokens will be sent to:<br /> <span class="mobile">@Model.CountryCode @Model.Phone</span></p>
                </div>
                <div class="col-md-6 col-xs-12 banner_bottom_left">
                    <div class="d-flex card-payment">
                        <h3 class="text-left w-100">Enter your Card for Secure Payment</h3>
                        <div class="payment-form">
                            <form asp-controller="Customers" asp-action="Charge" name="formToken" id="formToken" method="post" class="form-horizontal">
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="stripeToken" id="stripeToken" value="" />
                                <input type="hidden" name="Amount" id="Amount" value="@Model.ChargeAmount" />
                            </form>
                            <div class="cell example example2" id="example-2">
                                <form asp-controller="Account" asp-action="XXX" method="post" class="form-horizontal">
                                    @Html.AntiForgeryToken()
                                    <ul>
                                        <li>
                                            <div id="example2-card-number" class="input empty"></div>
                                            <label for="example2-card-number" data-tid="elements_examples.form.card_number_label">Card Number</label>
                                            <div class="baseline"></div>
                                        </li>
                                        <li class="inline">
                                            <div id="example2-card-expiry" class="input empty"></div>
                                            <label for="example2-card-expiry" data-tid="elements_examples.form.card_expiry_label">Expiration</label>
                                            <div class="baseline"></div>
                                        </li>
                                        <li class="inline">
                                            <div id="example2-card-cvc" class="input empty"></div>
                                            <label for="example2-card-cvc" data-tid="elements_examples.form.card_cvc_label">CVC</label>
                                            <div class="baseline"></div>
                                        </li>
                                        <li>
                                            <button type="submit" class="btn" data-tid="elements_examples.form.pay_button">Pay & Complete Order</button>
                                            <div class="error" role="alert">
                                                <span class="message"></span>
                                            </div>
                                        </li>
                                    </ul>
                                </form>
                            </div>
                        </div>
                    </div>

                    <a href="~/customers/buy" class="btn btn-block btn-danger" style="margin-top: 8px">Or Go back</a>

                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>



@section ScriptsTop
    {
    <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript" src="~/js/stripemain.js" data-rel-js></script>
}

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Customers/Failed.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}



@section Styles
    {
    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 8em;
        }
    </style>
}

@{
    ViewData["Title"] = "Purchase Failed";
}


@model PurchaseForm


<div class="banner_bottom">
    <div class="container">
        <div class="inner_sec_info_wthree_agile">
            <div class="help_full">
                <h2 class="text-center">Your Purchase Failed</h2>
                <p class="text-center" style="font-size:1.2em;">We were unable to complete your purchase, <a href="~/customers/home">click here to try and purchase FunTokenz</a> once more.</p>
            </div>
        </div>
    </div>
</div>
    

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Customers/Home.cshtml
@using System.Globalization

@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}

@model PurchasesView

@{
    ViewData["Title"] = "Home";
}

@section Styles
    {
    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 0em;
        }

        .banner_bottom {
            padding-bottom: 0;
        }

        .breadcrumb-1 {
            background: #F4F9FE;
        }

        .panel1 {
            padding: 28px;
            margin: 20px 0px 30px 0px;
            border: 1px solid rgba(150, 200, 250, 0.1);
            background: rgba(150, 200, 250, 0.1);
            box-shadow: 0px 0px 20px rgb(0 0 0 / 30%);
            border: 10px solid #FFF;
            border-radius: 10px;
        }

        .panel {
            margin: 20px 0px 30px 0px;
            padding: 14px;
            border: 1px solid rgba(150, 200, 250, 0.1);
        }

        .total {
            text-align: right;
            color: #303030;
            padding: 16px 36px;
            background: #f1f1f1;
            font-weight: 600;
        }

        .tokens-list {
            width: 100%;
            margin-top: 10px;
        }

        .text-left {
            text-align: left !important;
        }

        .each-token {
            width: 100%;
            flex-direction: row;
            padding: 20px 28px;
            background-color: #F4F5F7;
            justify-content: space-between;
            margin-top: 16px;
        }

        .text-danger {
            color: #dc3545 !important;
        }
        .each-token h5.price {
            text-align: right;
            font-weight: 600;
        }

        .token-info span {
            text-align: left;
            color: #868a9a;
        }

        .token-info h5 {
            text-align: left;
            color: #15294b;
            margin-bottom: 10px;
        }

        .each-token h5.price span {
            font-size: 14px;
            font-weight: 600;
            background: #FFF;
            border-radius: 3px;
          
            padding: 2px;
            color: #15294b;
        }

        .mt-4, .my-4 {
            margin-top: 1.5rem !important;
        }

        .align-items-center {
            -ms-flex-align: center !important;
            align-items: center !important;
        }

        .d-flex {
            display: -ms-flexbox !important;
            display: flex !important;
        }

        .mr-2, .mx-2 {
            margin-right: 0.5rem !important;
        }

        .d-md-none {
            display: none !important;
        }

        img {
            vertical-align: middle;
            border-style: none;
        }

        .mt-3, .my-3 {
            margin-top: 1rem !important;
        }

        .w-100 {
            width: 100% !important;
        }

        .btn{
            padding: 6px 6px;
        }

    </style>
}



<div class="container-fluid breadcrumb-1" style="margin-top: 8.1em">
    <div class="row">
        <p style="padding: 0.5em 0 0 1em"><a href="~/">Home</a> . Customers Home</p>
    </div>
</div>



<div class="banner_bottom">
    <div class="container">
        <div class="inner_sec_info_wthree_agile">
            <div class="help_full">
                <div class="col-md-6 col-xs-12 banner_bottom_grid help">
                    <h2>Purchase Tokens</h2>
                    <div class="panel1">
                        <p>
                            <b>Purchase Fun Tokenz and start spending across our network of supported merchants.</b><br /><br />Tokens can be purchased in your local currency online, once purchased your tokenz will be available within your account and emailed or sent in a SMS to you. They can then be redeemed instantly with our supported partners.
                        </p>
                        <a href="~/customers/buy/" class="btn btn-block btn-danger font-weight-bold">Get Started - Purchase Fun Tokenz</a>
                    </div>
                </div>
                <div class="col-md-6 col-xs-12 banner_bottom_left">
                    <h2>My Tokens</h2>
                    <div class="panel resultspanel">
                        @if (Model.PurchaseRecords.Purchases.Count == 0)
                        {
                            <p>You have not purchased any Fun Tokenz to show.</p>
                        }
                        else
                        {
                            @await Html.PartialAsync("_Tokens", Model)
                        }
                    </div>

                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript">
        var endpoint = "/customers/home";
    </script>

    @{ await Html.RenderPartialAsync("_ResultsScriptsPartial"); }
}

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Customers/Success.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}


@{
    ViewData["Title"] = "Purchase Success";
}


@section Styles
    {
    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 8em;
        }

    </style>
}

@model PurchaseForm


<div class="banner_bottom">
    <div class="container">
        <div class="inner_sec_info_wthree_agile">
            <div class="help_full">
                <h2 class="text-center">Your Purchase Was Successful</h2>
                <p class="text-center" style="font-size:1.2em;">The recipient will receive a SMS message shortly on the phone number you provided, with their FunTokenz Code.<br />Simply use this FunTokenz code with any of our eligible partners to redeem your FunTokenz. <br />The tokens are valid for 24 months.</p>
            </div>
        </div>
    </div>
</div>