code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Models/View/AccessViews.cs
using FunTokenz.Models.Business;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FunTokenz.Models.View
{
    public class SignInView : ViewModelBase
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }

        public string JoinType { get; set; }
    }

    public class JoinView : ViewModelBase
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email Address")]
        public string Email { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Mobile")]
        public string Phone { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "CountryCode")]
        public string CountryCode { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        public string ConfirmPassword { get; set; }

        [Range(typeof(bool), "true", "true", ErrorMessage = "You must agree to the terms and conditions")]
        [Display(Name = "Terms and Conditions Verification")]
        public bool Agree { get; set; }

        public string CompanyName { get; set; }

        public string CompanyNumber { get; set; }
        public string JoinType { get; set; }

        public string Currency { get; set; }

    }

    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }

    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }
}

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FunTokenz.Filter;
using FunTokenz.Models.Business;
using FunTokenz.Models.Data;
using FunTokenz.Models.View;
using FunTokenz.Services;
using System.Security.Claims;
using System.Linq.Dynamic.Core;

namespace FunTokenz.Controllers
{
    public class AccessController : Controller
    {
        private readonly ILogger<AccessController> _logger;
        private readonly IRDS _RDS;
        private readonly IIdentity _Identity;
        private readonly IComms _Comms;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public AccessController(
                ILogger<AccessController> logger, 
                IRDS RDS, 
                IIdentity Identity, 
                IComms Comms,
                UserManager<ApplicationUser> userManager, 
                SignInManager<ApplicationUser> signInManager)
        {
            _logger = logger;
            _RDS = RDS;
            _Identity = Identity;
            _Comms = Comms;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [Route("oops")]
        [AllowAnonymous]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("/signout")]
        public async Task<IActionResult> Signout()
        {
            await _signInManager.SignOutAsync();
            HttpContext.Session.Clear();
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        [HttpGet]   
        [AllowAnonymous]
        [MustBeSignedOut]
        [Route("/customers/signin")]
        public IActionResult CustomersSignin(string returnUrl = null)
        {
            SignInView model = new SignInView();
            ViewData["ReturnUrl"] = returnUrl;
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [MustBeSignedOut]
        [Route("/customers/signin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CustomersSignIn(SignInView model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
                var user = await _userManager.FindByEmailAsync(model.Email);

                if (result.Succeeded && user.Type == "C")
                {
                    //if (string.IsNullOrEmpty(returnUrl) || returnUrl.Contains("signin") || returnUrl.Contains("join") || returnUrl.Contains("reset-password"))
                    //{
                    //    return RedirectToLocal(Url.Content("~") + "/customers/home");
                    //}
                    //else
                    //{
                    //    return Redirect(returnUrl);
                    //}

                    return RedirectToLocal(Url.Content("~") + "/customers/home");
                }
                else
                {
                    await _signInManager.SignOutAsync();
                    HttpContext.Session.Clear();

                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                    
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpGet]
        [Route("/customers/join")]
        [MustBeSignedOut]
        [AllowAnonymous]
        public IActionResult CustomersJoin(string returnUrl = null)
        {
            JoinView model = new JoinView();
            ViewData["ReturnUrl"] = returnUrl;
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [MustBeSignedOut]
        [Route("/customers/join")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CustomersJoin(JoinView model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;

            if (ModelState.IsValid)
            {

                if (_Identity.IsUniquePhonenumber(model.CountryCode, model.Phone))
                {
                    // If phone number is not unique, something failed, redisplay form
                    ModelState.AddModelError(string.Empty, "Phone number already exists");
                    return View(model);
                }

                var user = new ApplicationUser { Type = "C", CompanyName = model.CompanyName, CompanyNumber = model.CompanyNumber, UserName = model.Email, Email = model.Email, PhoneNumber = model.Phone, CountryCode = model.CountryCode, DatetimeJoined = Convert.ToInt64(DateTime.Now.ToUniversalTime().ToString("yyyyMMddHHmmssffff")), Firstname = model.FirstName, Lastname = model.LastName, EmailConfirmed = false };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    //var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    //var callbackUrl = Url.Action(nameof(Confirmed), "Access", new { userId = user.Id, code = code }, protocol: HttpContext.Request.Scheme);

                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToLocal(Url.Content("~") + "/customers/home");
                    
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        /* * */

        [HttpGet]
        [AllowAnonymous]
        [MustBeSignedOut]
        [Route("/resellers/signin")]
        public IActionResult ResellersSignin(string returnUrl = null)
        {
            SignInView model = new SignInView();
            ViewData["ReturnUrl"] = returnUrl;
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [MustBeSignedOut]
        [Route("/resellers/signin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResellersSignIn(SignInView model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
                var user = await _userManager.FindByEmailAsync(model.Email);

                if (result.Succeeded && user.Type == "R")
                {
                    //if (string.IsNullOrEmpty(returnUrl) || returnUrl.Contains("signin") || returnUrl.Contains("join") || returnUrl.Contains("reset-password"))
                    //{
                    //    return RedirectToLocal(Url.Content("~") + "/customers/home");
                    //}
                    //else
                    //{
                    //    return Redirect(returnUrl);
                    //}

                    if(user.ResellerApproved == true)
                    {
                        return RedirectToLocal(Url.Content("~") + "/resellers/home");
                    }

                    return RedirectToLocal(Url.Content("~") + "/resellers/awaiting-approval");
                }
                else
                {
                    await _signInManager.SignOutAsync();
                    HttpContext.Session.Clear();

                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpGet]
        [Route("/resellers/join")]
        [MustBeSignedOut]
        [AllowAnonymous]
        public IActionResult ResellersJoin(string returnUrl = null)
        {
            JoinView model = new JoinView();
            ViewData["ReturnUrl"] = returnUrl;
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [MustBeSignedOut]
        [Route("/resellers/join")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResellersJoin(JoinView model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;

            if (ModelState.IsValid)
            {

                
                if (_Identity.IsUniquePhonenumber(model.CountryCode, model.Phone))
                {
                    // If phone number is not unique in database, something failed, redisplay form
                    ModelState.AddModelError(string.Empty, "Phone number already exists");
                    return View(model);
                }

                var user = new ApplicationUser { Type = "R", ResellerApproved = false, ResellerCurrency = model.Currency, CompanyName = model.CompanyName, CompanyNumber = model.CompanyNumber, UserName = model.Email, Email = model.Email, PhoneNumber = model.Phone, CountryCode = model.CountryCode, DatetimeJoined = Convert.ToInt64(DateTime.Now.ToUniversalTime().ToString("yyyyMMddHHmmssffff")), Firstname = model.FirstName, Lastname = model.LastName, EmailConfirmed = false };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Access/CustomersJoin.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}

@model JoinView

@{
    ViewData["Title"] = "Join";
}

@section Styles
    {
    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 7em;
        }

        .banner_bottom {
            padding-bottom: 0;
        }


        .signin-form select {
            background: none;
            display: block;
            width: 100%;
            padding: 0.6em;
            font-size: 1em;
            margin: 0.5em 0;
            outline: none;
            color: #212121;
            border: none;
            border: 1px solid #ccc;
            letter-spacing: 1px;
            text-align: left;
        }
        .banner_bottom {
            background: #BFFFFA;
        }
    </style>
}




<div class="banner_bottom">
    <div class="container">
        <div class="row">
            <div class="inner_sec_info_wthree_agile">
                <div class="help_full">

                    <div class="col-md-6 col-sm-6 banner_bottom_left">
                        <h1>Pay & Play</h1>
                        <p>
                            Create a Fun Tokenz digital wallet for use with our Merchants anywhere, anytime. 
                            It's simple and free to create a wallet with us, deposit tokens by purchasing in your
                            local currency and access a new way to pay with our Merchants.
                        </p>
                    </div>
                    <div class="col-md-6 col-sm-6 banner_bottom_grid help">
                        <!---728x90--->
                        <div class="signin-form">
                            <h2 style="text-align: start">Open a wallet</h2>
                            <p style="font-size: 11pt; text-align: start">
                                Join thousands of customers and start paying in Fun Tokenz. 
                                Opening an account is Free.
                            </p>
                            <form aspasp-controller="Access" asp-action="CustomersJoin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                                <input type="hidden" asp-for="JoinType" value="C">
                                <div asp-validation-summary="All" class="text-danger"></div>


                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <input type="text" placeholder="First Name" asp-for="FirstName">
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" placeholder="Last Name" asp-for="LastName">
                                        </div>
                                    </div>
                                </div>



                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <select asp-for="CountryCode" id="country_code">
                                                <option value="+61">+61</option>
                                                <option value="+692">+692</option>
                                                <option value="+691">+691</option>
                                                <option value="+685">+685</option>
                                                <option value="+680">+680</option>
                                                <option value="+679">+679</option>
                                                <option value="+678">+678</option>
                                                <option value="+677">+677</option>
                                                <option value="+676">+676</option>
                                                <option selected value="+675">+675</option>
                                                <option value="+674">+674</option>
                                            </select>
                                        </div>
                                        <div class="col-md-9">
                                                <input oninput="this.value = this.value.replace(/[^0-9+ -]/g, '').replace(/(\..*)\./g, '$1');" type="text" class="phonenumber" placeholder="Mobile Number" asp-for="Phone">
                                        </div>
                                    </div>
                                </div>


                                <div class="form-group">
                                    <input type="email" asp-for="Email" placeholder="Enter your email address" required="">
                                </div>

                         
                                <div class="form-group">
                                    <input type="password" placeholder="Password" asp-for="Password" required>
                                </div>
                                <div class="form-group">
                                    <input type="password" placeholder="Confirm Password" asp-for="ConfirmPassword">
                                </div>

                                <div style="text-align: start">
                                    <input asp-for="Agree" class="form-check form-check-input" type="checkbox" value="true" id="defaultCheck1" checked>
                                    <label class="form-check-label" for="defaultCheck1">By creating an account you agree to our Terms of Service</label>
                                </div>

                                <div class="tp" style="margin-top: 1em">
                                    <button type="submit" class="btn btn-danger btn-block btn-outline-danger">Sign up</button>
                                </div>
                            </form>

                            <p style="margin-top: 1em">
                                <a href="~/customers/signin"> Or sign in</a>
                            </p>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>

@*@section Scripts
{
    <script type="text/javascript" src="~/js/jquery.maskedinput.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#country_code").change(function(){
                var code = $(this).val();

                if(code === "+61"){
                    $(".phonenumber").mask("999-999-999");
                } else if (code === "+692" || code === "+691") {
                    $(".phonenumber").mask("999-999-9");
                }else if(code === "+691"){
                    $(".phonenumber").mask("999-999");
                }
            });
            $('.phonenumber').css("padding", '7.5px');
            $('.phonenumber').css("font-size", '12pt');
        });
    </script>
}*@

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Access/CustomersSignin.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}


@model SignInView

@{
    ViewData["Title"] = "Sign In";
}

@section Styles
{
   <style>
       .inner_sec_info_wthree_agile {
           margin-top: 7em;
       }
       .banner_bottom{
           padding-bottom: 0;
       }

       .banner_bottom {
           background: #BFFFFA;
       }
    </style>
}

<div class="banner_bottom">
    <div class="container">
        <div class="row">
            <div class="inner_sec_info_wthree_agile">
                <div class="help_full">
              
                    <div class="col-md-6 col-sm-6 banner_bottom_left">
                        <h1>PAY & PLAY</h1>
                        <p>
                            Create a Fun Tokenz digital wallet for use with our Merchants anywhere,
                            anytime. It's simple and free to create a wallet with us, deposit tokens
                            by purchasing in your local currency and access a new way to pay with our
                            Merchants.
                        </p>
                    </div>

                    <div class="col-md-6 col-sm-6 banner_bottom_grid help">

                        <!---728x90--->
                        <div class="signin-form">
                            <h2 style="text-align: start">Sign In</h2>
                            <p style="font-size: 11pt; text-align: start">Sign in to purchase Fun Tokenz and manage your Fun Tokenz Wallet.</p>
                            <form asp-controller="Access" asp-action="CustomersSignin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                                <input type="hidden" asp-for="JoinType" value="C">

                                <div asp-validation-summary="All" class="text-danger"></div>

                                <input type="email" asp-for="Email" placeholder="Enter your email address" required="">
                                <input type="password" asp-for="Password" placeholder="Enter your password" required="">

                                <div style="text-align: start">
                                    <input asp-for="RememberMe" class="form-check form-check-input" type="checkbox" value="true" id="defaultCheck1" checked>
                                    <label class="form-check-label" for="defaultCheck1">Remember Me</label>
                                </div>

                                <div class="tp" style="margin-top: 1em">
                                    <button type="submit" class="btn btn-danger btn-block btn-outline-danger">Signin</button>
                                </div>
                            </form>

                            <p style="margin-top: 1em">
                                <a href="~/customers/join"> Or create a wallet</a>
                            </p>

                            <p>
                                <a style="color: #D9534F" href="~/reset"> Forgot your password?</a>
                            </p>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Access/MerchantsJoin.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}

@model JoinView

@{
    ViewData["Title"] = "Join";
}

@section Styles
    {
    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 7em;
        }

        .banner_bottom {
            padding-bottom: 0;
        }


        .signin-form select {
            background: none;
            display: block;
            width: 100%;
            padding: 0.6em;
            font-size: 1em;
            margin: 0.5em 0;
            outline: none;
            color: #212121;
            border: none;
            border: 1px solid #ccc;
            letter-spacing: 1px;
            text-align: left;
        }

       

    </style>
}

<div class="banner_bottom">
    <div class="container">
        <div class="row">
            <div class="inner_sec_info_wthree_agile">
                <div class="help_full">

                    <div class="col-md-6 col-sm-6 banner_bottom_left">
                        <h1>ACCEPT FUN TOKENZ</h1>
                        <p>
                            Expand your services to new customers by becoming a Fun Tokenz merchant.
                            Our secure wallet and payment system can be easily integrated into your business,
                            simply express your interest with us to become a participating Merchant.
                        </p>
                    </div>
                    <div class="col-md-6 col-sm-6 banner_bottom_grid help">
                        <!---728x90--->
                        <div class="signin-form">
                            <h2 style="text-align: start">Express your interest</h2>
                            <p style="font-size: 11pt; text-align: start">Expand your customer base by accepting FunTokenz, it's simple to integrate securely into your digital checkouts with our API.</p>
                            <form asp-controller="Access" asp-action="MerchantsJoin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                                <input type="hidden" asp-for="JoinType" value="M">
                                <div asp-validation-summary="All" class="text-danger"></div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <input type="text" placeholder="First Name" asp-for="FirstName">
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" placeholder="Last Name" asp-for="LastName">
                                        </div>
                                    </div>
                                </div>



                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <select asp-for="CountryCode">
                                                <option value="+61">+61</option>
                                                <option value="+692">+692</option>
                                                <option value="+691">+691</option>
                                                <option value="+685">+685</option>
                                                <option value="+680">+680</option>
                                                <option value="+679">+679</option>
                                                <option value="+678">+678</option>
                                                <option value="+677">+677</option>
                                                <option value="+676">+676</option>
                                                <option selected value="+675">+675</option>
                                                <option value="+674">+674</option>
                                            </select>
                                        </div>
                                        <div class="col-md-9">
                                                <input oninput="this.value = this.value.replace(/[^0-9+ -]/g, '').replace(/(\..*)\./g, '$1');" type="text" placeholder="Mobile Number" asp-for="Phone">
                                        </div>
                                    </div>
                                </div>


                                <div class="form-group">
                                    <input type="email" asp-for="Email" placeholder="Enter your email address" required="">
                                </div>

                                <div class="form-group">
                                    <input type="text" placeholder="Company Name" asp-for="CompanyName">
                                </div>
                                <div class="form-group">
                                    <input type="text" placeholder="Company / Tax Number" asp-for="CompanyNumber">
                                </div>
                                <div class="form-group">
                                    <input type="password" placeholder="Password" asp-for="Password" required>
                                </div>
                                <div class="form-group">
                                    <input type="password" placeholder="Confirm Password" asp-for="ConfirmPassword">
                                </div>

                                <div style="text-align: start">
                                    <input asp-for="Agree" class="form-check form-check-input" type="checkbox" value="true" id="defaultCheck1" checked>
                                    <label class="form-check-label" for="defaultCheck1">By creating an account you agree to our Terms of Service</label>
                                </div>

                                <div class="tp" style="margin-top: 1em">
                                    <button type="submit" class="btn btn-danger btn-block btn-outline-danger">Sign up</button>
                                </div>
                            </form>

                            <p style="margin-top: 1em">
                                <a href="~/merchants/signin"> Or sign in</a>
                            </p>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>

code/websiteft_2022/websiteft/FunTokenz/FunTokenz/Views/Access/NewPasswordConfirmation.cshtml
@{
    Layout = Layout = "~/Views/Shared/_Layout1.cshtml";
}

@{
    ViewData["Title"] = "Password Reset";
}

@section Styles
    {
    <style>
        .inner_sec_info_wthree_agile {
            margin-top: 0em;
        }

        .breadcrumb-1 {
            background: #F4F9FE;
        }
    </style>
}

<div class="container-fluid breadcrumb-1" style="margin-top: 8.1em">
    <div class="row">
        <p style="padding: 0.5em 0 0 1em"><a href="~/">Home</a> . Set new password</p>
    </div>
</div>


<div class="banner_bottom">
    <div class="container">
        <div class="row">
            <div class="inner_sec_info_wthree_agile">
                <div class="help_full">
                    <div class="col-md-3 col-sm-12"></div>
                    <div class="col-md-6 col-sm-12 banner_bottom_grid help">
                        <!---728x90--->
                        <div class="signin-form">
                            <h2 style="text-align: start">Set new password.</h2>
                            <p style="font-size: 11pt; text-align: start">Your password has been reset, please sign in below.</p>

                            <div style="text-align: start">
                                <p style="margin-top: 1em">
                                    <a href="~/customers/signin"> Customers sign in</a><br />
                                    <a href="~/merchants/signin"> Merchants sign in</a><br />
                                    <a href="~/resellers/signin"> Resellers sign in</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3  col-sm-12"></div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>